
version: "3.8"

services:
  sqlite-browser:
    container_name: sqlite-browser
    image: linuxserver/sqlitebrowser:latest
    ports:
      - "8000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - sqlite_data:/data
    restart: unless-stopped


#  fish-shop-telebot:
#    container_name: fish-shop-telebot
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      BOT_TOKEN: ${FISH_TOKEN}
#      DB_PATH: "/sqlite/fish_shop.db"
#      ADMIN_IDS: ${ADMIN_IDS}
#      PAYMENT_TOKEN: ${FISH_PAYMENT_TOKEN}
#      TZ: Europe/Kiev
#    restart: unless-stopped
#    volumes:
#      - sqlite_data:/sqlite


  quad-bike-shop-aiogram:
    container_name: quad-bike-shop-aiogram
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: ${QUAD_BOT_TOKEN}
      DB_PATH: "/sqlite/quad_shop.db"
      ADMIN_IDS: ${ADMIN_IDS}
      PAYMENT_TOKEN: ${QUAD_PAYMENT_TOKEN}
      TZ: Europe/Kiev
    restart: unless-stopped
    volumes:
      - sqlite_data:/sqlite


volumes:
  sqlite_data:

